name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: cannectivity
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: cannectivity
          toolchains: arm-zephyr-eabi
          ccache-cache-key: ${{ matrix.os }}

      - name: Build firmware
        working-directory: cannectivity
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Print ccache stats
        if: runner.os != 'Windows'
        run: |
          ccache -s -vv
